# Generated by Django 4.1.2 on 2022-10-26 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('endereco', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('data_lancamento', models.DateTimeField()),
                ('valor_locacao', models.FloatField()),
                ('Categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrega', models.DateTimeField()),
                ('data_locacao', models.DateTimeField()),
                ('valor', models.FloatField()),
                ('Cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.cliente')),
                ('Filme', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.filme')),
            ],
        ),
    ]
